# Generated by Django 5.1.4 on 2024-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='Deadlines',
        ),
        migrations.AddField(
            model_name='deadline',
            name='Amount_of_debts',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество долгов'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='Extra_time',
            field=models.DateField(blank=True, null=True, verbose_name='Доп. время'),
        ),
        migrations.AlterField(
            model_name='deadline',
            name='Type_of_deadlines',
            field=models.TextField(blank=True, null=True, verbose_name='Замечание:'),
        ),
        migrations.DeleteModel(
            name='Debts',
        ),
    ]
