# Generated by Django 5.1.4 on 2024-12-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_deadline_deadlines_deadline_amount_of_debts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deadline',
            name='Amount_of_debts',
        ),
        migrations.AddField(
            model_name='deadline',
            name='Answers_or_debts',
            field=models.CharField(blank=True, default=0, null=True),
        ),
    ]
