# Generated by Django 5.1.4 on 2024-12-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_deadline_amount_of_debts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='Answers_or_debts',
            field=models.CharField(blank=True, null=True),
        ),
    ]
