# Generated by Django 5.1.4 on 2024-12-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_eventorg_eventmem_delete_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['Name'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['Character_ID__Name'], 'verbose_name': 'Дедлайн', 'verbose_name_plural': 'Дедлайны'},
        ),
        migrations.AlterModelOptions(
            name='eventorg',
            options={'ordering': ['Date_of_event'], 'verbose_name': 'Ивент', 'verbose_name_plural': 'Ивенты'},
        ),
    ]
