# Generated by Django 5.1.4 on 2024-12-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_character_options_alter_deadline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('viewer', 'Просматривающий'), ('member', 'Участник')], default='viewer', max_length=20),
        ),
    ]
